version: '2.0'
services:
  db_async:
    image: postgres
    container_name: db_async
    restart: always
    ports:
      - 5123:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_pw
      POSTGRES_DB: postgres_database
    volumes:
      - ./pData:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    healthcheck:      
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -t 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s

  auth:
    container_name: auth
    restart: on-failure
    depends_on:
      db_async:
        condition: service_healthy
      mqtt-broker:
        condition: service_started
    # image: auth
    build:
      context: .
      dockerfile: auth.dockerfile
    ports:
      - 5000:5000     
    links: 
        - db_async

  log:
    container_name: log
    restart: on-failure
    depends_on:
      db_async:
        condition: service_healthy
      mqtt-broker:
        condition: service_started
    # image: log
    build:
      context: .
      dockerfile: log.dockerfile
    ports:
      - 5100:5100     
    links: 
        - db_async

  image:
    container_name: image
    restart: on-failure
    depends_on:
      db_async:
        condition: service_healthy
    # image: image
    build:
      context: .
      dockerfile: image.dockerfile
    ports:
      - 5200:5200     
    links: 
        - db_async

  mqtt-broker:
    container_name: mqtt
    image: eclipse-mosquitto:latest
    volumes:
      - ./mosquitto/config:/mosquitto/config
    ports:
    - target: 1891
      published: 1891
      protocol: tcp
      mode: host
    - target: 9001
      published: 9001
      protocol: tcp
      mode: host

  gateway:
    build: 
      dockerfile: nginx.dockerfile
    ports:
      - "8000:80"
    depends_on:
      - auth
      - log
      - image